/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Form;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nickk
 */
public class CreateProfile extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    Form form;
    public CreateProfile(Form form) {
        initComponents();
        this.form = form;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workArea = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtUniqueIdNum = new javax.swing.JTextField();
        btnPhoto = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtBankAccount = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lblMedRecNum = new javax.swing.JLabel();
        txtVehicleNum = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblHealthNum = new javax.swing.JLabel();
        txtDeviceNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblIp = new javax.swing.JLabel();
        txtLinkedin = new javax.swing.JTextField();
        lblUniqueIdNum = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblBankAccount = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleNum = new javax.swing.JLabel();
        lblDeviceNum = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblImagePath = new javax.swing.JLabel();

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 204));

        workArea.setMaximumSize(new java.awt.Dimension(40000, 40000));

        lblName.setText("Name");

        lblLocation.setText("Location");

        btnPhoto.setText("Upload");
        btnPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        lblSsn.setText("SSN");

        lblDob.setText("DOB");

        txtLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumActionPerformed(evt);
            }
        });

        lblMedRecNum.setText("Medical Record Number");

        lblPhone.setText("Phone");

        lblLinkedin.setText("Linkedin");

        lblHealthNum.setText("Health Beneficiary Number");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblIp.setText("IP Address");

        lblUniqueIdNum.setText("Unique ID Number");

        lblFax.setText("FAX");

        lblBankAccount.setText("Bank Account Number");

        lblEmail.setText("Email");

        lblLicenseNum.setText("Certificate / License Number");

        lblVehicleNum.setText("Vehicle License Plate Number");

        lblDeviceNum.setText("Device ID Number");

        lblPhoto.setText("Photo");

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREATE");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImagePath.setText("Image Directory");

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(btnPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(workAreaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(workAreaLayout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName)
                                .addComponent(lblPhoto)
                                .addComponent(lblUniqueIdNum)
                                .addComponent(lblIp)
                                .addComponent(lblLinkedin)
                                .addComponent(lblDeviceNum)
                                .addComponent(lblVehicleNum)
                                .addComponent(lblLicenseNum)
                                .addComponent(lblBankAccount)
                                .addComponent(lblMedRecNum)
                                .addComponent(lblSsn)
                                .addComponent(lblEmail)
                                .addComponent(lblFax)
                                .addComponent(lblPhone)
                                .addComponent(lblDob)
                                .addComponent(lblLocation)
                                .addComponent(lblHealthNum))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUniqueIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70))
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(workAreaLayout.createSequentialGroup()
                            .addGap(299, 299, 299)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workAreaLayout.createSequentialGroup()
                .addContainerGap(695, Short.MAX_VALUE)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagePath))
                .addGap(64, 64, 64))
            .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(workAreaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblName)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLocation)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDob)
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhone)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFax)
                        .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSsn)
                        .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMedRecNum)
                        .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHealthNum)
                        .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankAccount)
                        .addComponent(txtBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLicenseNum)
                        .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVehicleNum)
                        .addComponent(txtVehicleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeviceNum)
                        .addComponent(txtDeviceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLinkedin)
                        .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIp)
                        .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUniqueIdNum)
                        .addComponent(txtUniqueIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(lblPhoto)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jScrollPane1.setViewportView(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String errorFields = "";
        String incomFields="";
        if(txtName.getText() == ""){
                incomFields += "Name"; 
        }
        else
        form.setName(txtName.getText());
        
        form.setLocation(txtLocation.getText());
        
        String Dob =txtDob.getText();
        if(Dob.length() !=10 || false == Dob.matches("[0-9]+")){
            errorFields += " Date of Birth";
        }
        else
        form.setDob(txtDob.getText());
        
        
        String tele = txtPhone.getText();
        if(tele.length() !=10 || false == tele.matches("[0-9]+")){
            errorFields += ", Phone";
        }
        else
        form.setTele(txtPhone.getText());
        
        String fax =txtFax.getText();
        if(fax.length() !=10 || false == fax.matches("[0-9]+")){
            errorFields += ", Fax";
        }
        else
        form.setFax(txtFax.getText());
        
        String Email = "txtEmail.getText()";
        if(false == Email.matches("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\\\.[A-Z]{2,6}$")){
            errorFields += ", Email";
        form.setEmail(txtEmail.getText());
        
        String Ssn = "txtSsn.getText()";
        if(Ssn.length() !=9 || false == Ssn.matches("[0-9]+")){
            errorFields += ", Ssn";
        }
        else
        form.setSsn(txtSsn.getText());
        
        String MedRecNum = txtMedRecNum.getText();
        if(false == MedRecNum.matches("^[a-zA-Z0-9]+$")){
            errorFields += ", Medical Record Number";
        }
        else
        form.setMedRecNum(txtMedRecNum.getText());
        
        String HealthNum = txtHealthNum.getText();
        if(false == HealthNum.matches("^[a-zA-Z0-9]+$")){
            errorFields += ", Health Plan Beneficiary Number";
        }
        else
        form.setHealthNum(txtHealthNum.getText());
        
        String BankAccount = txtBankAccount.getText();
        if(false == BankAccount.matches("[0-9]+")){
            errorFields += ", BankAccount ";
        }
        else
        form.setBankAccount(txtBankAccount.getText());
        
        String LicenseNum = txtLicenseNum.getText();
        if(false == LicenseNum.matches("^[a-zA-Z0-9]+$")){
            errorFields += ", Certificate / License Number";
        }
        else
        form.setLicenseNum(txtLicenseNum.getText());
        
        String VehicleNum = txtVehicleNum.getText();
        if(false == VehicleNum.matches("^[a-zA-Z0-9]+$")){
            errorFields += ", Vehicle License Plate Number";
        }
        else
        form.setVehicleNum(txtVehicleNum.getText());
        
        String DeviceIdNum = txtDeviceNum.getText();
        if(false == DeviceIdNum.matches("[0-9]+")){
            errorFields += ", Device ID Number ";
        }
        else
        form.setDeviceNum(txtDeviceNum.getText());
        
        form.setLinkedin(txtLinkedin.getText());
        
        String Ip = txtIp.getText();
        if(false == Ip.matches("[0-9]+")){
            errorFields += ", IP Address";
        }
        else
        form.setIp(txtIp.getText());
        
        if(lblImagePath.getText() == ""){
                incomFields += ", Photo "; 
        }
        else
        form.setPhoto(lblImagePath.getText());
        
        form.setUniqueIdNum(txtUniqueIdNum.getText());
        
        String output = "saved";
        if(incomFields != "")
            output = " Please check your entries "+ incomFields;
        if(errorFields != "")
            output += "\n Please check your incorrect entries "+ errorFields;
        
        JOptionPane.showMessageDialog(this, output);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        String path;
        JFileChooser selector = new JFileChooser();
        selector.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter extensions = new FileNameExtensionFilter("*Images","jpg","png", "jpeg");
        selector.addChoosableFileFilter(extensions);

        int status = selector.showSaveDialog(null);

        if(status == JFileChooser.APPROVE_OPTION){
            File selectedImage = selector.getSelectedFile();

            path =selectedImage.getAbsolutePath();
            lblImagePath.setText(path);
    }//GEN-LAST:event_btnPhotoActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblDeviceNum;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHealthNum;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueIdNum;
    private javax.swing.JLabel lblVehicleNum;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtUniqueIdNum;
    private javax.swing.JTextField txtVehicleNum;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
