/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.Form;
import javax.swing.ImageIcon;

/**
 *
 * @author nickk
 */
public class ViewProfile extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfile
     */
    Form form;
    public ViewProfile( Form form) {
        initComponents();
        this.form = form;
        
        displayForm();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workArea = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        lblMedRecNum = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblHealthNum = new javax.swing.JLabel();
        lblIp = new javax.swing.JLabel();
        lblUniqueIdNum = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblBankAccount = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleNum = new javax.swing.JLabel();
        lblDeviceNum = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtUniqueIdNum = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtMedRecNum = new javax.swing.JTextField();
        txtBankAccount = new javax.swing.JTextField();
        txtLicenseNum = new javax.swing.JTextField();
        txtVehicleNum = new javax.swing.JTextField();
        txtDeviceNum = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 204));

        workArea.setMaximumSize(new java.awt.Dimension(40000, 40000));

        lblName.setText("Name");

        lblLocation.setText("Location");

        lblSsn.setText("SSN");

        lblDob.setText("DOB");

        lblMedRecNum.setText("Medical Record Number");

        lblPhone.setText("Phone");

        lblLinkedin.setText("Linkedin");

        lblHealthNum.setText("Health Beneficiary Number");

        lblIp.setText("IP Address");

        lblUniqueIdNum.setText("Unique ID Number");

        lblFax.setText("FAX");

        lblBankAccount.setText("Bank Account Number");

        lblEmail.setText("Email");

        lblLicenseNum.setText("Certificate / License Number");

        lblVehicleNum.setText("Vehicle License Plate Number");

        lblDeviceNum.setText("Device ID Number");

        lblPhoto.setText("Image");

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpActionPerformed(evt);
            }
        });

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });

        txtSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsnActionPerformed(evt);
            }
        });

        txtLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDob, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMedRecNum)
                    .addComponent(lblHealthNum)
                    .addComponent(lblBankAccount)
                    .addComponent(lblLicenseNum)
                    .addComponent(lblVehicleNum)
                    .addComponent(lblDeviceNum)
                    .addComponent(lblLinkedin)
                    .addComponent(lblIp)
                    .addComponent(lblUniqueIdNum)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSsn)
                    .addComponent(lblEmail)
                    .addComponent(lblFax))
                .addGap(202, 202, 202)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUniqueIdNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDob, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSsn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBankAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVehicleNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDeviceNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHealthNum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1331, 1331, 1331))
        );

        workAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBankAccount, lblDeviceNum, lblDob, lblEmail, lblFax, lblHealthNum, lblImage, lblIp, lblLicenseNum, lblLinkedin, lblLocation, lblMedRecNum, lblName, lblPhone, lblPhoto, lblSsn, lblTitle, lblUniqueIdNum, lblVehicleNum});

        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation)
                    .addComponent(lblLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDob)
                    .addComponent(lblDob))
                .addGap(9, 9, 9)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblFax))
                .addGap(11, 11, 11)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSsn, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lblSsn))
                .addGap(18, 18, 18)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedRecNum)
                    .addComponent(lblMedRecNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHealthNum)
                    .addComponent(lblHealthNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankAccount)
                    .addComponent(lblBankAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicenseNum)
                    .addComponent(lblLicenseNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleNum)
                    .addComponent(lblVehicleNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeviceNum)
                    .addComponent(lblDeviceNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedin)
                    .addComponent(lblLinkedin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIp)
                    .addComponent(lblIp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUniqueIdNum)
                    .addComponent(lblUniqueIdNum))
                .addGap(18, 18, 18)
                .addGroup(workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoto))
                .addGap(757, 757, 757))
        );

        jScrollPane1.setViewportView(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpActionPerformed

    private void txtSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblDeviceNum;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHealthNum;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMedRecNum;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueIdNum;
    private javax.swing.JLabel lblVehicleNum;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtDeviceNum;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtUniqueIdNum;
    private javax.swing.JTextField txtVehicleNum;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private void displayForm() {
                

         txtName.setText(form.getName());
        txtLocation.setText(form.getLocation());
        txtDob.setText(form.getDob());
        txtPhone.setText(form.getTele());
        txtFax.setText(form.getFax());
        txtEmail.setText(form.getEmail());
        txtSsn.setText(form.getSsn());
        txtMedRecNum.setText(form.getMedRecNum());
        txtHealthNum.setText(form.getHealthNum());
        txtBankAccount.setText(form.getBankAccount());
        txtLicenseNum.setText(form.getLicenseNum());
        txtVehicleNum.setText(form.getVehicleNum());
        txtDeviceNum.setText(form.getDeviceNum());
        txtLinkedin.setText(form.getLinkedin());
        txtIp.setText(form.getIp());
        ImageIcon ic = new ImageIcon(form.getPhoto());
        lblImage.setText(form.getPhoto());
        lblImage.setIcon(ic);        
        txtUniqueIdNum.setText(form.getUniqueIdNum());
        

    }
}
